version: '3'

services:
  flowers_bot:
    build: .
    container_name: flowers_care_bot
    restart: always
    volumes:
      - ./docker_files/JSON_data:/Docker/JSON_data
      - ./docker_files/log:/Docker/log/
      - ./docker_files/database:/Docker/database
